name: Build new release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        volumes:
          - "/tmp/sccache:/data"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@master
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
        driver-opts: network=${{ job.services.redis.network }}
    - name: Cache Docker sccache
      uses: actions/cache@v2
      with:
        # this is horrible as you can't set the path but it probably works see:
        # https://github.com/moby/buildkit/issues/1474
        # https://github.com/moby/buildkit/issues/1512
        path: /tmp/sccache
        key: ${{ runner.os }}-docker-sccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-sccache-
    - name: Inspect cache in
      run: |
        ls -lah /tmp/sccache
        du -sh /tmp/sccache
        cat /etc/resolv.conf
    - name: Save sccache to disk
      env:
        NETWORK: ${{ job.services.redis.network }}
      run: |
        docker run --network=$NETWORK redis redis-cli -h redis SAVE
    - name: Build Dependency layers
      uses: docker/build-push-action@v2
      with:
        push: false
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=${{ runner.temp }}/docker-buildx-cache
        cache-to: type=local,dest=${{ runner.temp }}/docker-buildx-cache-new,mode=max
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        network: ${{ job.services.redis.network }}
    - name: Save sccache to disk
      env:
        NETWORK: ${{ job.services.redis.network }}
      run: |
        docker run --network=$NETWORK redis redis-cli -h redis SAVE
    - name: Inspect cache out
      run: |
        ls -lah /tmp/sccache
        du -sh /tmp/sccache
